export type ModEntry={id:number;name:string;zh?:string;version:string;category:string;side:"双端"|"客户端"|"服务端";channel:string;description:string};
export const modCategories=["全部","航空与载具","轨道与城市","工业与化学","计算与安防","探索与太空","东方幻想","建筑与文化","性能与图形","基础依赖","本地组件"] as const;
export const mods:ModEntry[]=[
[1,"Advanced Peripherals","高级外设","1.21.1-0.7.62b","计算与安防","双端","Beta","扩展 CC:Tweaked 的传感器、自动化接口与外设。"],
[2,"Aeronautics Hot Air Fix","","1.1.1","性能与图形","客户端","正式","修复 Create Aeronautics 热气流等效果。"],
[3,"Almost Unified","统一材料 / 配方","1.21.1-1.4.2+neoforge","工业与化学","双端","正式","统一多个科技模组重复材料与配方输出。"],
[4,"Applied Energistics 2","应用能源 2","19.2.17","计算与安防","双端","正式","数字存储网络、终端与自动合成。"],
[5,"Architectury API","","13.0.11+neoforge","基础依赖","双端","正式","跨加载器公共 API。"],
[6,"Athena","","4.0.6","基础依赖","客户端","正式","连接纹理与装饰方块客户端支持。"],
[7,"CC: Tweaked","可编程电脑","1.120.2","计算与安防","双端","Alpha","Lua 计算机、海龟、显示器与网络。"],
[8,"Chemical Science","","1.21.1-3.1.2","工业与化学","双端","正式","化学、材料与实验型工业内容。"],
[9,"Chunky","区块预生成","1.4.23","性能与图形","服务端","正式","维护窗口预生成世界区块。"],
[10,"Colorwheel","","1.2.9+mc1.21.1","性能与图形","客户端","正式","Iris/Sodium 环境中的 Create/Flywheel 渲染桥。"],
[11,"Create","机械动力","6.0.10+mc1.21.1","工业与化学","双端","正式","旋转动力、加工、物流、移动结构和列车。"],
[12,"Create Aeronautics","机械动力航空学","1.3.1+mc1.21.1","航空与载具","双端","正式","将 Create 方块组装成可移动航空器。"],
[13,"Cybernetics","赛博改造","0.5.2-HOTFIX","计算与安防","双端","正式","身体强化与赛博改造路线。"],
[14,"Distant Horizons","遥远地平线","3.2.0-b-1.21.1","性能与图形","客户端","Beta","用 LOD 显示远景。"],
[15,"Electrodynamics","","1.21.1-1.0.13","工业与化学","双端","正式","电力、线缆、机器与工程体系。"],
[16,"Eternal Starlight","永恒星光","0.9.0+1.21.1+neoforge","探索与太空","双端","正式","独立新维度、环境、生物和结构。"],
[17,"Exposure","摄影","1.9.18","建筑与文化","双端","正式","相机、胶片与作品展示。"],
[18,"Exposure: Expanded","","1.0.1","建筑与文化","双端","正式","扩展 Exposure 拍摄与展示能力。"],
[19,"Exposure: Space","","1.2.7","探索与太空","双端","正式","把摄影延伸到太空场景。"],
[20,"FerriteCore","铁氧体核心","7.0.3-neoforge","性能与图形","双端","正式","降低数据内存占用。"],
[21,"FramedBlocks","框架方块","10.6.1","建筑与文化","双端","正式","可套用材质与形状的框架方块。"],
[22,"Fusion (Connected Textures)","","1.3.14-neoforge-mc1.21.1","性能与图形","客户端","正式","连接纹理与模型表现。"],
[23,"Geckolib","","4.9.2","基础依赖","双端","正式","动画运行库。"],
[24,"GuideME","","21.1.17","基础依赖","双端","正式","游戏内指南与文档框架。"],
[25,"ImmediatelyFast","","1.6.13+1.21.1","性能与图形","客户端","正式","优化 GUI、粒子等即时渲染。"],
[26,"Immersive Aircraft","沉浸式飞机","1.4.6+1.21.1","航空与载具","双端","正式","传统实体飞机。"],
[27,"Immersive Melodies","沉浸式旋律","0.7.1+1.21.1","建筑与文化","双端","正式","乐器、旋律同步与多人表演。"],
[28,"Iris Shaders","","1.8.14-beta.1+1.21.1-neoforge","性能与图形","客户端","Beta","NeoForge 光影加载器。"],
[29,"Iris Veil Compat","","1.21.1+0.3.0-beta","性能与图形","客户端","Beta","Iris 与 Veil 兼容。"],
[30,"Lithium","","mc1.21.1-0.15.4-neoforge","性能与图形","双端","正式","优化逻辑与 tick 路径。"],
[31,"Mekanism","通用机械","10.7.19.85","工业与化学","双端","正式","矿物处理、气体、化工、物流与储能。"],
[32,"Mekanism Generators","","10.7.19.85","工业与化学","双端","正式","Mekanism 发电设备。"],
[33,"Minecraft Transit Railway","我的世界铁路","NEOFORGE-4.1.0-beta.2+1.21.1","轨道与城市","双端","Beta","城市地铁、车站、线路和自动运行车辆。"],
[34,"ModernFix","","5.27.20+mc1.21.1","性能与图形","双端","正式","改善启动、内存和兼容路径。"],
[35,"Moonlight Lib","","1.21.1-3.4.1","基础依赖","双端","正式","公共运行库。"],
[36,"Oritech","","1.2.10","工业与化学","双端","正式","工业机器、激光、资源加工与无人机。"],
[37,"Potentials","","0.7.1","基础依赖","双端","Beta","Stellaris 基础接口。"],
[38,"Rechiseled","再雕刻","1.2.5-neoforge-mc1.21","建筑与文化","双端","正式","大量装饰纹理。"],
[39,"Sable","","2.0.5+mc1.21.1","航空与载具","双端","正式","Aeronautics 移动子世界、物理与保存基础。"],
[40,"SecurityCraft","安全工艺","v1.10.2.1","计算与安防","双端","正式","加固方块、密码设备、摄像头和扫描设施。"],
[41,"ServerCore","","1.5.19+1.21.1","性能与图形","服务端","正式","服务端性能与距离管理。"],
[42,"Sodium","钠","mc1.21.1-0.8.12-neoforge","性能与图形","客户端","正式","客户端核心渲染优化。"],
[43,"spark","","1.10.124-neoforge-1.21.1","性能与图形","服务端","正式","TPS、MSPT、CPU 与内存诊断。"],
[44,"Steam ’n’ Rails","蒸汽与铁轨","0.3.0-beta.2+neoforge-mc1.21.1","轨道与城市","双端","Beta","扩展 Create 轨道与机车。"],
[45,"Stellaris","","1.4.25","探索与太空","双端","正式","主太空栈，提供火箭、星球与远征。"],
[46,"SuperMartijn642’s Config Lib","","1.1.8-neoforge-mc1.21","基础依赖","双端","正式","统一配置框架。"],
[47,"SuperMartijn642’s Core Lib","","1.1.24-neoforge-mc1.21","基础依赖","双端","正式","公共核心代码。"],
[48,"Touhou Little Maid","东方女仆","1.5.3-neoforge+mc1.21.1","东方幻想","双端","正式","女仆、互动、祭坛与协作内容。"],
[49,"Touhou Little Maid: Spell","东方女仆：法术","1.8.4-neoforge","东方幻想","双端","正式","东方女仆法术扩展。"],
[50,"Vista","电视与媒体","1.21.1-5.4.4","建筑与文化","双端","正式","电视、屏幕、镜面和影院展示。"],
[51,"Voltaic","","1.21.1-1.0.12","基础依赖","双端","正式","Electrodynamics 电力基础。"],
[52,"Refurbished Furniture","现代家具","1.0.22","建筑与文化","双端","外部锁定","交互家具、电器和现代内装。"],
[53,"Framework","","0.13.11","基础依赖","双端","外部锁定","Refurbished Furniture 公共运行框架。"],
[54,"Building Gadgets 2","建筑小帮手 2","1.3.9","建筑与文化","双端","外部锁定","批量放置、复制和辅助建造工具。"],
[55,"Haorenfu Compatibility Guard","好人服兼容保护","1.0.0","本地组件","双端","本地组件","好人服祭坛兼容保护。"],
[56,"Vista Aeronautics Fix","Vista 航空兼容修复","1.0.1","本地组件","客户端","本地组件","修复移动结构上的 Vista 渲染与频率问题。"]
].map(([id,name,zh,version,category,side,channel,description])=>({id:id as number,name:name as string,zh:(zh as string)||undefined,version:version as string,category:category as string,side:side as ModEntry["side"],channel:channel as string,description:description as string}));
export const excludedMods=[{name:"C2ME",reason:"避免给 Sable 移动子世界、物理与保存路径叠加额外异步区块变量。"},{name:"ScalableLux",reason:"避免叠加异步光照调度变量。"},{name:"Oculus",reason:"图形主链已锁定为 Iris + Sodium。"},{name:"Iris Flywheel Compat",reason:"与锁定的 Colorwheel 1.2.9 冲突。"},{name:"Entity Culling",reason:"与航空学仍有开放兼容风险。"},{name:"Creating Space / Northstar",reason:"属于 Stellaris 的替代太空主栈。"},{name:"WaterMedia",reason:"不增加第二套媒体后端。"}] as const;
export const verifiedShaders=[{name:"MakeUp – Ultra Fast",version:"9.5d",use:"均衡档起点，优先帧率"},{name:"Complementary Reimagined",version:"r5.8.1",use:"高画质通用方案"},{name:"Complementary Unbound",version:"r5.8.1",use:"成本更高的画质档"},{name:"Bliss",version:"2.1.0",use:"高画质备选"}] as const;
