export const server={name:"Minecraft 好人服务器",pack:"Haorenfu Universe",address:"Haorenfu.cn",port:"25565",group:"302805107",minecraft:"1.21.1",loader:"NeoForge 21.1.248",java:"Java 21（64 位）",publicClient:"1.2.0",auditedBaseline:"1.1.0",founded:"2013 年 5 月"} as const;
export const navigation=[{href:"/play",label:"世界玩法"},{href:"/mods",label:"模组百科"},{href:"/download",label:"加入游戏"},{href:"/community",label:"社区论坛"},{href:"/history",label:"世界沿革"},{href:"/security",label:"账号安全"}] as const;
export type GameplayPillar={slug:string;index:string;title:string;kicker:string;description:string;difficulty:string;crew:string;start:string;mods:string[];steps:string[];accent:"cyan"|"gold"|"violet"|"rose"};
export const gameplayPillars:GameplayPillar[]=[
{slug:"aeronautics",index:"01",title:"造物升空",kicker:"不是搭一架飞机，而是把整座工坊变成会飞的世界。",description:"先用沉浸式飞机熟悉天空，再把机械动力结构组装成可登乘、可交互的工程航空器。每一次首飞都需要重量、动力、网络与安全边界共同成立。",difficulty:"进阶",crew:"2–6 人",start:"约 2–4 小时",mods:["Create Aeronautics","Sable","Immersive Aircraft","Create"],steps:["实体飞机入门","建造旋转动力工坊","组装块结构航空器","建立公共航空港"],accent:"cyan"},
{slug:"rail-city",index:"02",title:"轨道之城",kicker:"让城市沿着时刻表生长。",description:"MTR 负责高密度公共交通，Create 列车与蒸汽铁轨负责工业物流和观光线路。两套轨道逻辑彼此独立，却能在同一座站城综合体中协作。",difficulty:"中等",crew:"2–12 人",start:"约 1–3 小时",mods:["Minecraft Transit Railway","Create","Steam ’n’ Rails"],steps:["勘测线路","修建首座车站","接入工业物流","运营跨城网络"],accent:"gold"},
{slug:"industry",index:"03",title:"工业纪元",kicker:"从第一根传动轴，到覆盖全服的材料网络。",description:"旋转动力、电力、化工和高科技制造层层推进；统一材料与配方让跨模组生产线真正连成体系，而不是彼此隔离的机器陈列。",difficulty:"进阶",crew:"1–8 人",start:"约 3–6 小时",mods:["Create","Mekanism","Oritech","Electrodynamics","Chemical Science"],steps:["机械加工","建立电网","气体与化工","全自动材料闭环"],accent:"gold"},
{slug:"smart-base",index:"04",title:"智慧基地",kicker:"让仓库、机器、传感器与安全系统学会合作。",description:"用 AE2 管理物资和自动合成，以可编程电脑与高级外设连接基地设施，再用 SecurityCraft 建立权限清晰的公共基础设施。",difficulty:"进阶",crew:"1–6 人",start:"约 3–5 小时",mods:["Applied Energistics 2","CC: Tweaked","Advanced Peripherals","SecurityCraft"],steps:["数字仓储","自动合成","编程与监控","分区安防"],accent:"cyan"},
{slug:"stars",index:"05",title:"奔向群星",kicker:"把远征当作一项全服工程。",description:"Stellaris 是唯一主太空栈。建设发射场、准备能源与补给、组织星球考察，并用太空摄影为每一次远征留下档案。",difficulty:"高阶",crew:"3–12 人",start:"约 6–12 小时",mods:["Stellaris","Exposure: Space","Mekanism","Applied Energistics 2"],steps:["科研与备料","建设发射中心","首次离地","建立星球前哨"],accent:"violet"},
{slug:"starlight",index:"06",title:"永恒星光",kicker:"在陌生维度里，把探险重新变成未知。",description:"独立维度、结构、生物与环境共同组成一条完整冒险线。团队需要建立安全前哨、记录路线，并谨慎处理跨维度设备和移动结构。",difficulty:"中高",crew:"2–8 人",start:"约 2–5 小时",mods:["Eternal Starlight","Exposure","SecurityCraft"],steps:["准备远征","寻找入口","勘探与摄影","建设维度前哨"],accent:"violet"},
{slug:"touhou",index:"07",title:"东方幻想",kicker:"女仆、法术与文化街区，共同生活在长期世界里。",description:"东方女仆与法术扩展构成协作、收集和幻想体验。祭坛附近有专门的兼容保护；复杂机械和移动载具必须遵守安全边界。",difficulty:"中等",crew:"1–6 人",start:"约 1–3 小时",mods:["Touhou Little Maid","Touhou Little Maid: Spell","Haorenfu Compatibility Guard"],steps:["认识祭坛规则","结识女仆伙伴","学习法术系统","建设幻想街区"],accent:"rose"},
{slug:"culture",index:"08",title:"建筑、影像与音乐",kicker:"一座长期世界，也应该拥有自己的记忆。",description:"现代家具、精细建筑、电视与影院、摄影和多人音乐演奏，让城市不只高效运转，也能保存活动、展览与玩家共同创作。",difficulty:"轻松",crew:"1–不限",start:"约 30 分钟",mods:["Refurbished Furniture","Vista","Exposure","Immersive Melodies","Rechiseled"],steps:["搭建空间","完成室内陈设","记录影像","举办放映与演出"],accent:"rose"}
];
export const joinSteps=[{number:"01",title:"准备正版 Java 版",body:"安装 64 位 Java 21。原版客户端、基岩版或其他加载器不能直接加入。"},{number:"02",title:"导入官方客户端",body:"在 Modrinth App 或 Prism Launcher 中导入 Haorenfu Universe 1.2.0 MRPACK；下载入口发布前仍需最终校验。"},{number:"03",title:"分配合适内存",body:"按整机内存从 4–8 GB 起步；16 GB 电脑默认分配 6 GB。不要把全部物理内存交给游戏，先完成一次无光影启动。"},{number:"04",title:"申请白名单并加入",body:"前往 QQ 群 302805107 按公告申请白名单。客户端已预置 Haorenfu.cn，默认端口 25565。"}] as const;
export const verifiedStats=[{value:"2013.05",label:"世界起点"},{value:"1.21.1",label:"Minecraft Java"},{value:"56",label:"1.1.0 可审计组件"},{value:"24 + 16",label:"1.2.0 资源包与光影"}] as const;
